spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edumerge
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
app:
  jwt-secret: change-this-development-secret-to-a-long-random-value-123456789
  jwt-expiration-ms: 86400000
